import type { Metadata } from 'next'
import Link from 'next/link'
import { createMetadata } from '@/lib/seo-config'
import { BreadcrumbJsonLd, FAQPageJsonLd, SoftwareApplicationJsonLd } from '@/components/seo/JsonLd'
import { Download, CheckCircle2, ArrowRight, Calculator, FileText, Check, ShieldCheck, BarChart3, Layers } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

export const metadata: Metadata = createMetadata({
  path: '/gst-filing-software-bhutan',
  title: 'Bhutan GST Filing Software — Automatic 5% GST Returns & Invoicing | Jinda POS',
  description: 'Effortless GST filing software in Bhutan. Jinda POS autocalculates 5% Bhutan GST on taxable sales, generates ready-to-file monthly GST returns, and issues tax-compliant invoices offline.',
  keywords: [
    'GST filing software Bhutan',
    'GST software Bhutan',
    'GST return software Bhutan',
    'Bhutan GST compliance',
    '5% GST Bhutan software',
    'tax filing software Bhutan',
    'POS GST software Bhutan',
  ],
})

const faqs = [
  {
    question: 'How does Jinda POS handle 5% GST in Bhutan?',
    answer: 'Jinda POS automatically applies the standard 5% Goods and Services Tax (GST) rate on all taxable product items during point-of-sale checkout. Non-taxable or exempt goods can easily be tagged to calculate 0% tax.',
  },
  {
    question: 'Does Jinda POS generate monthly GST returns for government filing?',
    answer: 'Yes! Jinda POS features a dedicated GST Return generator module. With one click, it computes total taxable sales, output tax collected, input tax paid on purchase orders, and net tax liability payable for monthly filing.',
  },
  {
    question: 'Are printed invoices compliant with Bhutan GST regulations?',
    answer: 'Yes. All thermal receipts and A4/A5 invoices generated by Jinda display your business TPN (Taxpayer Number), itemized 5% GST breakdowns, tax invoice headers, and legal customer transaction terms.',
  },
]

export default function GstFilingSoftwareBhutanPage() {
  return (
    <>
      <BreadcrumbJsonLd
        items={[
          { name: 'Home', url: 'https://jindapos.com' },
          { name: 'GST Filing Software in Bhutan', url: 'https://jindapos.com/gst-filing-software-bhutan' },
        ]}
      />
      <FAQPageJsonLd faqs={faqs} />
      <SoftwareApplicationJsonLd />

      <main className="flex flex-col min-h-screen bg-slate-50 dark:bg-slate-900/50">
        {/* Hero Section */}
        <section className="bg-gradient-to-br from-slate-950 via-bhutan-maroon-dark to-slate-900 text-white py-20 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-bhutan-gold/10 blur-[120px] rounded-full pointer-events-none" />
          <div className="container relative z-10 px-4 md:px-6 mx-auto text-center max-w-4xl space-y-6">
            <Badge className="bg-bhutan-gold text-bhutan-maroon-dark border-none px-4 py-1.5 rounded-full font-black tracking-widest uppercase text-xs">
              100% Tax Compliant Software for Bhutan
            </Badge>
            <h1 className="text-3xl sm:text-4xl md:text-6xl font-black tracking-tight leading-tight">
              Bhutan GST Filing & Accounting Software
            </h1>
            <p className="text-base sm:text-lg text-slate-300 max-w-2xl mx-auto leading-relaxed font-medium">
              Automate 5% Bhutan GST calculations on every sale, output compliant tax invoices, and export ready-to-file monthly GST returns — all completely offline.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center pt-4">
              <Link href="/download">
                <Button size="lg" className="w-full sm:w-auto bg-bhutan-gold text-bhutan-maroon-dark hover:bg-bhutan-gold-light font-black px-8 h-14 rounded-xl text-base shadow-xl">
                  <Download className="mr-2 h-5 w-5" /> Download Free Trial
                </Button>
              </Link>
              <Link href="/pricing">
                <Button size="lg" variant="outline" className="w-full sm:w-auto border-white/20 text-white hover:bg-white/10 font-bold px-8 h-14 rounded-xl text-base">
                  View Plans <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </Link>
            </div>
          </div>
        </section>

        {/* GST Steps */}
        <section className="py-16 md:py-24 container px-4 md:px-6 mx-auto max-w-6xl">
          <div className="text-center space-y-4 mb-16">
            <h2 className="text-2xl md:text-4xl font-black text-slate-900 dark:text-white">
              How Jinda Simplifies GST Compliance in 3 Steps
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <Card className="p-8 rounded-3xl border-slate-200 dark:border-slate-800">
              <CardContent className="p-0 space-y-4">
                <div className="h-12 w-12 rounded-2xl bg-bhutan-maroon text-white flex items-center justify-center font-black text-xl">
                  1
                </div>
                <h3 className="text-xl font-black text-slate-900 dark:text-white">Auto 5% Calculation</h3>
                <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
                  As you scan products at POS checkout, 5% GST is computed instantly per item with automatic tax invoice numbering.
                </p>
              </CardContent>
            </Card>

            <Card className="p-8 rounded-3xl border-slate-200 dark:border-slate-800">
              <CardContent className="p-0 space-y-4">
                <div className="h-12 w-12 rounded-2xl bg-bhutan-maroon text-white flex items-center justify-center font-black text-xl">
                  2
                </div>
                <h3 className="text-xl font-black text-slate-900 dark:text-white">Input & Output Tracking</h3>
                <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
                  Track GST paid on supplier purchases (Input Tax) and GST collected on sales (Output Tax) automatically in double-entry ledgers.
                </p>
              </CardContent>
            </Card>

            <Card className="p-8 rounded-3xl border-slate-200 dark:border-slate-800">
              <CardContent className="p-0 space-y-4">
                <div className="h-12 w-12 rounded-2xl bg-bhutan-maroon text-white flex items-center justify-center font-black text-xl">
                  3
                </div>
                <h3 className="text-xl font-black text-slate-900 dark:text-white">1-Click GST Returns</h3>
                <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed">
                  Generate comprehensive monthly GST summaries with single-click PDF / Excel exports ready for government tax filing.
                </p>
              </CardContent>
            </Card>
          </div>
        </section>

        {/* FAQs */}
        <section className="py-16 md:py-24 container px-4 md:px-6 mx-auto max-w-4xl space-y-10">
          <div className="text-center space-y-3">
            <h2 className="text-2xl md:text-4xl font-black text-slate-900 dark:text-white">GST Filing FAQs</h2>
          </div>
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="p-6 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 space-y-2">
                <h3 className="text-lg font-black text-slate-900 dark:text-white">{faq.question}</h3>
                <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed font-medium">{faq.answer}</p>
              </div>
            ))}
          </div>
        </section>
      </main>
    </>
  )
}
